# Generated by Django 2.2.7 on 2019-11-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Unknown', max_length=32)),
                ('userclearence', models.IntegerField(choices=[(1, 'Normal'), (2, 'VIP'), (3, 'SVIP')], default=1)),
                ('user_rank', models.IntegerField(default=0, max_length=3)),
            ],
        ),
    ]
