# Generated by Django 2.2.7 on 2019-11-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='user_rank',
            field=models.IntegerField(default=0),
        ),
    ]
