# Generated by Django 2.2.7 on 2019-11-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankdemo', '0002_auto_20191121_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='user_rank',
            new_name='score',
        ),
    ]
