# Generated by Django 2.2.7 on 2019-11-21 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankdemo', '0003_auto_20191121_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Unknown', max_length=32)),
                ('userclearence', models.IntegerField(choices=[(1, 'Normal'), (2, 'VIP'), (3, 'SVIP')], default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='rank',
            name='score',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='userclearence',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='username',
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('userinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rankdemo.Userinfo')),
                ('score', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('rankdemo.userinfo',),
        ),
    ]
