# Generated by Django 2.2.7 on 2019-11-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdemo', '0006_auto_20191122_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='username',
            field=models.CharField(default='Unknown', max_length=32),
        ),
    ]
