# Generated by Django 2.2.7 on 2019-11-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankdemo', '0007_auto_20191122_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='date',
        ),
    ]
