# Generated by Django 2.2.7 on 2019-11-22 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rankdemo', '0009_auto_20191122_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
