# Generated by Django 2.2.7 on 2019-11-22 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankdemo', '0011_auto_20191122_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='scores',
            new_name='score',
        ),
    ]
