# Generated by Django 2.2.7 on 2019-11-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdemo', '0012_auto_20191122_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='level',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
