# Generated by Django 2.2.7 on 2019-11-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdemo', '0014_auto_20191122_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='level',
            field=models.CharField(default='Not', max_length=16),
        ),
    ]
