# Generated by Django 2.2.7 on 2019-11-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankdemo', '0015_auto_20191122_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['-score']},
        ),
    ]
