# Generated by Django 2.2.7 on 2019-11-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdemo', '0017_auto_20191122_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
