# Generated by Django 2.2.7 on 2019-11-23 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankdemo', '0018_auto_20191123_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='level',
        ),
    ]
