# Generated by Django 2.2.7 on 2019-11-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdemo', '0020_gameresultview'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresultview',
            name='base64str',
            field=models.CharField(default='none', max_length=22),
        ),
    ]
