# Generated by Django 2.2.7 on 2019-11-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankdemo', '0023_auto_20191123_0334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameResultView',
            new_name='Share',
        ),
    ]
