# Generated by Django 2.2.7 on 2019-11-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankdemo', '0024_auto_20191127_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='base64str',
            field=models.CharField(default='none', max_length=34),
        ),
    ]
